mappings:
  # === Counters ===
  - match: "(.+)\\.(.+)_start$"
    match_metric_type: counter
    name: "custom_counter_job_start"
    match_type: regex
    labels:
      airflow_id: "$1"
      job_name: "$2"

  # === Gauges ===
  - match: "*.dag_processing.last_run.seconds_ago.*"
    match_metric_type: gauge
    name: "custom_gauge_dag_processing_last_run_seconds"
    labels:
      airflow_id: "$1"
      dag_file: "$2"

  # === Timers ===
  - match: "*.scheduler.critical_section_duration"
    match_metric_type: observer
    name: "custom_summary_scheduler_critical_section_duration"
    labels:
      airflow_id: "$1"
