{
 "title": "airflow",
 "time": { "from": "2025-07-06T21:08:01.586Z", "to": "2025-07-06T21:32:18.279Z" },
 "panels": [
  {
   "title": "airflow_asset_orphaned",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "airflow_asset_orphaned", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_dag_processing_file_path_queue_size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "airflow_dag_processing_file_path_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_dag_processing_file_path_queue_update_count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "airflow_dag_processing_file_path_queue_update_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_dag_processing_file_path_queue_update_count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "airflow_dag_processing_file_path_queue_update_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_dag_processing_import_errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "airflow_dag_processing_import_errors",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_dag_processing_processes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "airflow_dag_processing_processes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_dag_processing_total_parse_time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "airflow_dag_processing_total_parse_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_dag_processor_heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "airflow_dag_processor_heartbeat",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_dagbag_size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "targets": [
    { "expr": "airflow_dagbag_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_dagrun_dependency_check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "airflow_dagrun_dependency_check",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_dagrun_dependency_check_sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "airflow_dagrun_dependency_check_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_dagrun_dependency_check_count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "airflow_dagrun_dependency_check_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_dagrun_duration_success",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "airflow_dagrun_duration_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_dagrun_duration_success_sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "airflow_dagrun_duration_success_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_dagrun_duration_success_count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "airflow_dagrun_duration_success_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_executor_open_slots",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "targets": [
    { "expr": "airflow_executor_open_slots", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_executor_queued_tasks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "targets": [
    { "expr": "airflow_executor_queued_tasks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_executor_running_tasks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "targets": [
    { "expr": "airflow_executor_running_tasks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_pool_deferred_slots",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "targets": [
    { "expr": "airflow_pool_deferred_slots", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_pool_deferred_slots_default_pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "targets": [
    {
     "expr": "airflow_pool_deferred_slots_default_pool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_pool_open_slots",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "targets": [
    { "expr": "airflow_pool_open_slots", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_pool_open_slots_default_pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "airflow_pool_open_slots_default_pool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_pool_queued_slots",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "targets": [
    { "expr": "airflow_pool_queued_slots", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_pool_queued_slots_default_pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "targets": [
    {
     "expr": "airflow_pool_queued_slots_default_pool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_pool_running_slots",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "targets": [
    { "expr": "airflow_pool_running_slots", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_pool_running_slots_default_pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "airflow_pool_running_slots_default_pool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_pool_scheduled_slots",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "targets": [
    { "expr": "airflow_pool_scheduled_slots", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_pool_scheduled_slots_default_pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "airflow_pool_scheduled_slots_default_pool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_pool_starving_tasks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
   "targets": [
    { "expr": "airflow_pool_starving_tasks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_pool_starving_tasks_default_pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "targets": [
    {
     "expr": "airflow_pool_starving_tasks_default_pool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_scheduler_critical_section_query_duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "airflow_scheduler_critical_section_query_duration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_scheduler_critical_section_query_duration_sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 25 },
   "targets": [
    {
     "expr": "airflow_scheduler_critical_section_query_duration_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_scheduler_critical_section_query_duration_count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "airflow_scheduler_critical_section_query_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_scheduler_heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 25 },
   "targets": [
    { "expr": "airflow_scheduler_heartbeat", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_scheduler_orphaned_tasks_adopted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "airflow_scheduler_orphaned_tasks_adopted",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_scheduler_orphaned_tasks_cleared",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "targets": [
    {
     "expr": "airflow_scheduler_orphaned_tasks_cleared",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_scheduler_scheduler_loop_duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "airflow_scheduler_scheduler_loop_duration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_scheduler_scheduler_loop_duration_sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 30 },
   "targets": [
    {
     "expr": "airflow_scheduler_scheduler_loop_duration_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_scheduler_scheduler_loop_duration_count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "airflow_scheduler_scheduler_loop_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_scheduler_tasks_executable",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_executable",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_scheduler_tasks_starving",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_starving",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_serde_load_serializers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "targets": [
    { "expr": "airflow_serde_load_serializers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_serde_load_serializers_sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "airflow_serde_load_serializers_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_serde_load_serializers_count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 35 },
   "targets": [
    {
     "expr": "airflow_serde_load_serializers_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_task_instance_created",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 35 },
   "targets": [
    { "expr": "airflow_task_instance_created", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_task_instance_created_SQLExecuteQueryOperator",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "airflow_task_instance_created_SQLExecuteQueryOperator",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_task_instance_created_TriggerDagRunOperator",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "airflow_task_instance_created_TriggerDagRunOperator",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_task_instance_created__BranchPythonDecoratedOperator",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 35 },
   "targets": [
    {
     "expr": "airflow_task_instance_created__BranchPythonDecoratedOperator",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_task_instance_created__PythonDecoratedOperator",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "airflow_task_instance_created__PythonDecoratedOperator",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_task_scheduled_duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 40 },
   "targets": [
    {
     "expr": "airflow_task_scheduled_duration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_task_scheduled_duration_sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "airflow_task_scheduled_duration_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_task_scheduled_duration_count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "airflow_task_scheduled_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_ti_running",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 40 },
   "targets": [
    { "expr": "airflow_ti_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_triggerer_capacity_left",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 40 },
   "targets": [
    {
     "expr": "airflow_triggerer_capacity_left",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "airflow_triggerer_heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 45 },
   "targets": [
    { "expr": "airflow_triggerer_heartbeat", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "airflow_triggers_running",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 45 },
   "targets": [
    { "expr": "airflow_triggers_running", "legendFormat": "__auto" }
   ]
  }
 ]
}