{
 "title": "go_",
 "time": { "from": "2025-07-06T20:01:04.996Z", "to": "2025-07-06T20:08:37.244Z" },
 "panels": [
  {
   "title": "go_gc_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_gc_duration_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "targets": [
    { "expr": "go_gc_duration_seconds_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_gc_duration_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "targets": [
    { "expr": "go_gc_duration_seconds_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_gc_gogc_percent",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "targets": [
    { "expr": "go_gc_gogc_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_gc_gomemlimit_bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_gc_gomemlimit_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_info",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "targets": [
    { "expr": "go_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_buck_hash_sys_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "go_memstats_buck_hash_sys_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_frees_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "targets": [
    { "expr": "go_memstats_frees_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_gc_sys_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "targets": [
    { "expr": "go_memstats_gc_sys_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_heap_alloc_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_heap_idle_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "targets": [
    { "expr": "go_memstats_heap_idle_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_heap_inuse_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_heap_objects",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "targets": [
    { "expr": "go_memstats_heap_objects", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_heap_released_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "go_memstats_heap_released_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_heap_sys_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "targets": [
    { "expr": "go_memstats_heap_sys_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_last_gc_time_seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "go_memstats_last_gc_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_mallocs_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "targets": [
    { "expr": "go_memstats_mallocs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_mcache_inuse_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "targets": [
    { "expr": "go_memstats_mcache_inuse_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_mcache_sys_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "targets": [
    { "expr": "go_memstats_mcache_sys_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_mspan_inuse_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "targets": [
    { "expr": "go_memstats_mspan_inuse_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_mspan_sys_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "targets": [
    { "expr": "go_memstats_mspan_sys_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_next_gc_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "targets": [
    { "expr": "go_memstats_next_gc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_other_sys_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "targets": [
    { "expr": "go_memstats_other_sys_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_stack_inuse_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "targets": [
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_stack_sys_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
   "targets": [
    { "expr": "go_memstats_stack_sys_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_sys_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
   "targets": [
    { "expr": "go_memstats_sys_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_sched_gomaxprocs_threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "targets": [
    { "expr": "go_sched_gomaxprocs_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "targets": [
    { "expr": "go_threads", "legendFormat": "__auto" }
   ]
  }
 ]
}